### ISSUE TITLE
CommonAPI-D-Bus has a 'std::system_error' Abort with GCC4.7.3/stdc++, who can give a solution or suggestion?

### ISSUE THREAD

**Issue by liutiegang** [COVESA/capicxx-dbus-runtime#13]
Dear CommonAPI-D-Bus Project Owner,

I am working on porting DBUS and GENIVI CommonAPI/CommonAPI-D-Bus to QNX6.6&ARMV7&IMX6DL. Now everything is ok, only issue is :
For async call and async callback, DBusProxyAsyncCallbackHandler.hpp and DBusProxyAsyncSignalMemberCallbackHandler.hpp always throw:
 terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
I found the std::promise<CallStatus>.set_Value trigger it. I google some solutions, maybe this is a GCC4.7.3  bug or insufficiency for C++11 supporting.
My question is if there is solution or an alternative to fix or bypass this issue. for example, don't use std::promise/std::future ......
who can help me on it, any suggestion or solution would be appreciated.

Thanks,
TiegangLiu
444825423@qq.com

**Comment by liutiegang** [comment]
Dear CommonAPI-D-Bus Project Owner,

BTY, I have already tried to use std::packaged_task replace std::promise, but failed.

I found this : https://rextester.com/BSSE88988, seems is the same root cause.

Do you have a solution using the non-c++11 or any c++11 skill/way to bypass it, and as succinct as possible.

I am very wanted to use CommonAPI-D-Bus, it is a great IPC solution.

Thanks.

**Comment by goncaloalmeida** [comment]
@liutiegang you are still with this problem?
